name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Get Version
        id: get_version
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_NAME#v}" # strip leading 'v'
          echo "dll_version=${VERSION}.${{ github.run_number }}" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Restore
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore \
            /p:Version=${{ steps.get_version.outputs.dll_version }} \
            /p:AssemblyVersion=${{ steps.get_version.outputs.dll_version }} \
            /p:FileVersion=${{ steps.get_version.outputs.dll_version }}

      - name: Pack
        run: dotnet pack --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.get_version.outputs.version }}

      - name: Publish
        run: dotnet nuget push "artifacts/*.nupkg" --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json